artifacts_root: artifacts     #main folder is artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion  #under artifacts i created data ingestion folder
  source_URL: 'https://drive.google.com/uc?id=1CscVSu8TXjX8ePy4YeO6nX8oeDWGoQgG'   #donload url
  local_data_file: artifacts/data_ingestion/data.zip   #output=data.zip
  unzip_dir: artifacts/data_ingestion  #unzip in data ingestion folder

#1st write this yaml file for data ingesion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
#2nd step for base model

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5

  #1st update config.yaml